-- Rowkwy Hotspotting
--insert into hbase.customer select * from ssb.customer;
--insert into hbase.dates select * from ssb.dates;
--insert into hbase.lineorder select * from ssb.lineorder;
--insert into hbase.part select * from ssb.part;
--insert into hbase.supplier select * from ssb.supplier;
